# Railway configuration for frontend service
[build]
builder = "dockerfile"
dockerfilePath = "dockerfile"

[deploy]
startCommand = "streamlit run streamlit_app.py --server.port=$PORT --server.address=0.0.0.0"
